### PR TITLE
Fix: Compiling error

### LINKED ISSUE #32: Project fails compiling
```bash
src/github/issuereporter.ts(25,22): error TS2709: Cannot use namespace 'Octokit' as a type.
src/github/issuereporter.ts(34,28): error TS2351: This expression is not constructable.
  Type 'typeof import("/home/site/utils/node_modules/@octokit/rest/index")' has no construct signatures.
src/github/issuereporter.ts(51,44): error TS2694: Namespace '"/home/site/utils/node_modules/@octokit/rest/index"' has no exported member 'SearchIssuesResponseItemsItem'.
src/github/issuereporter.ts(61,45): error TS2694: Namespace '"/home/site/utils/node_modules/@octokit/rest/index"' has no exported member 'SearchIssuesResponseItemsItem'.
src/github/issuereporter.ts(68,48): error TS2694: Namespace '"/home/site/utils/node_modules/@octokit/rest/index"' has no exported member 'IssuesUpdateParams'.
src/github/issuereporter.ts(73,22): error TS2694: Namespace '"/home/site/utils/node_modules/@octokit/rest/index"' has no exported member 'IssuesUpdateParams'.
src/github/issuereporter.ts(206,51): error TS7006: Parameter 'label' implicitly has an 'any' type.
src/github/issuereporter.ts(225,52): error TS2694: Namespace '"/home/site/utils/node_modules/@octokit/rest/index"' has no exported member 'SearchIssuesResponseItemsItem'.
```

/cc @hxlnt @sarvaje

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #32

### CODE REVIEW

File: packages/utils/src/github/issuereporter.ts [hunk 1]
```diff
@@ -11,6 +11,101 @@ type GithubData = {
     repo: string;
 }
 
+/*
+ * Octokit/types doesn't define a type for the items in a search and
+ * doesn't export the type IssuesUpdateEndpoint.
+ * These are a copy/paste of what they have in their code.
+ * Any suggestion to do this in a better way?
```
Comment (molant) [inline packages/utils/src/github/issuereporter.ts:18]: Is there an issue opened reporting this? If so can you put the link in here?

Comment (sarvaje) [reply packages/utils/src/github/issuereporter.ts:18]: No, but I can open it.

Comment (sarvaje) [reply packages/utils/src/github/issuereporter.ts]: Now the types looks better hehehe. They say that in 2-3 months they will have names for the types.
